Feature/create company
MohamedNiaissa/CareerProjectSymfony pull request #3
Opened 2022-11-08 16:33 UTC by MohamedNiaissa

2022-11-08 16:50 UTC, MohamedNiaissa commented on src/Controller/CompanyController.php
> +    public function companyPage()
quelle est la route associée? a supprimer si inutile

2022-11-08 16:50 UTC, MohamedNiaissa commented on src/Controller/CompanyController.php
> +    #[Route('/company', name: 'company')]
endpoint au pluriel /companies et /companies/id

2022-11-08 16:50 UTC, MohamedNiaissa commented on src/Controller/CompanyController.php
> +    #[Route('/company', name: 'company')]
/companies/new et name create_company

2022-11-08 16:50 UTC, MohamedNiaissa commented on src/Entity/Company.php
> +    #[ORM\Column(length: 255, nullable: true)]
attention els url peuvent rapidement avoir plus de 255 char

2022-11-08 18:43 UTC, Maghwyn requested changes
Il manque le history.md, je m'en occupe.

2022-11-08 18:43 UTC, Maghwyn commented on src/Controller/CompanyController.php
> +    public function companyPage()
A toi de définir les routes nécessaires, on fera une review si il y a un problème quelque part.

2022-11-08 18:48 UTC, Maghwyn approved these changes
Je vais tirer une branche juste pour le setup du history.md.

2022-11-08 18:50 UTC, merged

2022-11-08 18:59 UTC, artmoni commented
@Maghwyn tu as mergé mais il restait des modifs pour que la PR soit finalisée ?

2022-11-08 19:00 UTC, artmoni commented
je t'invite a delete la branche de travail quand tu merge également, et t'assurer de squash les commits

2022-11-09 08:20 UTC, MohamedNiaissa commented on src/Controller/CompanyController.php
> +    public function companyPage()
fix

2022-11-09 08:21 UTC, MohamedNiaissa commented on src/Controller/CompanyController.php
> +    #[Route('/company', name: 'company')]
fix

2022-11-09 09:23 UTC, MohamedNiaissa commented on src/Entity/Company.php
> +    #[ORM\Column(length: 255, nullable: true)]
fix with 900 instead of 255